[package]
name = "domain-patterns"
version = "0.1.0"
authors = ["Peter Farr <Peter@PrismaPhonic.com>"]
description = "Domain patterns holds patterns from the world of Domain Driven Design."
keywords = ["domain", "design", "patterns", "database", "architecture"]
categories = ["database", "data-structures", "rust-patterns"]
repository = "https://github.com/prismaphonic/domain-patterns"
documentation = "https://docs.rs/domain-patterns"
readme = "README.md"
license = "MIT"
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]

[dev-dependencies]
regex = "1.2.1"
